name: Build/release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js and Yarn
        uses: actions/setup-node@v2
        with:
          node-version: 14
          cache: 'yarn'

      - name: Install dependencies
        run: yarn

      - name: Bundle with webpack and esbuild
        run: yarn run prod

      - name: Updater
        run: git update-index --chmod=+x ./gen-update-xml.sh && sh ./gen-update-xml.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install Snap
        run: |
          sudo snap install snapcraft --classic

      - name: Build Linux
        if: matrix.os == 'ubuntu-latest'
        run: npm run release --linux
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
